framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed
        reset_on_message: true
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: {}
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            notification:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    queue_name: "notification"
                retry_strategy:
                    # update the retry value!
                    max_retries: 0
                    delay: 10000
                    multiplier: 2
                    max_delay: 0
            form:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    queue_name: "form"
                retry_strategy:
                    max_retries: 3
                    delay: 10000
                    multiplier: 2
                    max_delay: 0
            background:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    queue_name: "background"
                retry_strategy:
                    max_retries: 3
                    delay: 60000
                    multiplier: 2
                    max_delay: 0
            sync:
                dsn: "sync://"
                retry_strategy:
                    max_retries: 0
            failed: "doctrine://default?queue_name=failed"

        routing:
            # Route your messages to the transports
            'App\Message\GovukNotify\VerificationEmailMessage': notification
            'App\Message\GovukNotify\VerificationSMSMessage': notification
            'App\Message\GovukNotify\SaveAndReturnEmailMessage': notification
            'App\Message\GovukNotify\ResetMemorableLinkEmailMessage': notification
            'App\Message\GovukNotify\SubmissionFailureEmailMessage': notification
            'App\Message\SubmissionMessage': form
            'App\Message\RunJobMessage': background
