# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
    email:
        digits: 6
        enabled: true
        mailer: App\Security\TwoFactorAuthMailer  # Use alternative service to send the authentication code
        template: admin/security/2fa_form.html.twig   # Template used to render the authentication form
