controllers:
    resource: ../src/Controller/
    type: annotation
    prefix: /notify

kernel:
    resource: ../src/Kernel.php
    type: annotation
    prefix: /notify

when@dev:
    redirect:
        path: /
        controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
        defaults:
            path: '/notify'

    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix:   /_error
    
    web_profiler_wdt:
        resource: '@WebProfilerBundle/Resources/config/routing/wdt.xml'
        prefix: /_wdt

    web_profiler_profiler:
        resource: '@WebProfilerBundle/Resources/config/routing/profiler.xml'
        prefix: /_profiler